replicaCount: 2

image:
  repository: 009946608368.dkr.ecr.ap-northeast-2.amazonaws.com/awsmarket
  tag: 2024-01-30T01-30-48
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-secret

service:
  type: NodePort
  port: 8080
  nodePort: 30007  # 선택한 노드 포트 번호

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
