replicaCount: 2

image:
  repository: 754677352307.dkr.ecr.ap-northeast-2.amazonaws.com/yous-test-ecr1
  tag: 2024-02-05T09-55-10
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-secret

service:
  type: NodePort
  port: 8080
  nodePort: 30007  # 선택한 노드 포트 번호

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
